// KP Horary 1..249 sub-table.
//
// Traditional Krishnamurti Paddhati horary uses a table of 249 sub-divisions
// across the zodiac. Sub-divisions are generated by the standard 27-nakshatra
// × 9-Vimshottari-sub scheme (243 subs). Whenever a sub crosses a 30° sign
// boundary it is SPLIT into two rows, one per sign. That produces exactly 249
// rows across the zodiac.

const VIM = ["Ketu","Venus","Sun","Moon","Mars","Rahu","Jupiter","Saturn","Mercury"] as const;
type V = typeof VIM[number];
const VIM_YEARS: Record<V, number> = {
  Ketu: 7, Venus: 20, Sun: 6, Moon: 10, Mars: 7,
  Rahu: 18, Jupiter: 16, Saturn: 19, Mercury: 17,
};
const NAK_SPAN = 360 / 27;

export type Horary249Row = {
  n: number;                    // 1..249
  sign: number;                 // 0..11
  startLon: number;             // absolute 0..360
  endLon: number;               // absolute 0..360
  nakshatra: number;            // 0..26
  starLord: V;
  subLord: V;
};

let CACHE: Horary249Row[] | null = null;

export function kp249Table(): Horary249Row[] {
  if (CACHE) return CACHE;

  // Step 1: raw 243 subs across the zodiac.
  type Raw = { startLon: number; endLon: number; nakshatra: number; starLord: V; subLord: V };
  const raw: Raw[] = [];
  for (let nak = 0; nak < 27; nak++) {
    const nakStart = nak * NAK_SPAN;
    const starLord = VIM[nak % 9];
    const startIdx = VIM.indexOf(starLord);
    let offset = 0;
    for (let k = 0; k < 9; k++) {
      const sub = VIM[(startIdx + k) % 9];
      const span = (VIM_YEARS[sub] / 120) * NAK_SPAN;
      raw.push({
        startLon: nakStart + offset,
        endLon: nakStart + offset + span,
        nakshatra: nak,
        starLord,
        subLord: sub,
      });
      offset += span;
    }
  }

  // Step 2: split any sub crossing a 30° boundary.
  const rows: Horary249Row[] = [];
  let n = 1;
  for (const r of raw) {
    const startSign = Math.floor(r.startLon / 30);
    const endSign = Math.floor((r.endLon - 1e-9) / 30);
    if (startSign === endSign) {
      rows.push({ n: n++, sign: startSign, ...r });
    } else {
      const boundary = (startSign + 1) * 30;
      rows.push({ n: n++, sign: startSign, startLon: r.startLon, endLon: boundary, nakshatra: r.nakshatra, starLord: r.starLord, subLord: r.subLord });
      rows.push({ n: n++, sign: endSign, startLon: boundary, endLon: r.endLon, nakshatra: r.nakshatra, starLord: r.starLord, subLord: r.subLord });
    }
  }

  CACHE = rows;
  return rows;
}

export function horaryRowByNumber(num: number): Horary249Row | null {
  const t = kp249Table();
  if (num < 1 || num > t.length) return null;
  return t[num - 1];
}
