import type { ArrowPolarity, Digit } from "./types";

/**
 * Every arrow is defined by one line of the magic square plus the polarity it
 * reads. A `strength` arrow forms when all three cells are present; a
 * `caution` arrow forms when all three cells are empty.
 */
export type ArrowDef = {
  key: string;
  name: string;
  line: readonly [Digit, Digit, Digit];
  polarity: ArrowPolarity;
  meaning: string;
  strengths: string;
  weaknesses: string;
  career: string;
  relationships: string;
  money: string;
  health: string;
  advice: string;
};

export const ARROW_DEFS: readonly ArrowDef[] = [
  {
    key: "determination",
    name: "Arrow of Determination",
    line: [4, 5, 6],
    polarity: "strength",
    meaning: "Practical thinking, balance and warmth are joined, so intentions convert into finished work.",
    strengths: "Persistence, steadiness under load, ability to finish what was promised.",
    weaknesses: "Stubbornness once a direction is chosen, difficulty accepting a better route midway.",
    career: "Excellent for long projects, operations, construction, product delivery and institution building.",
    relationships: "Dependable presence. Partners rely on your word, though flexibility needs practice.",
    money: "Wealth accumulates through consistency rather than through sudden gains.",
    health: "Overwork is the main risk. Fatigue is noticed only after it becomes physical.",
    advice: "Review direction every quarter so determination never hardens into rigidity.",
  },
  {
    key: "planning",
    name: "Arrow of Planning",
    line: [4, 3, 8],
    polarity: "strength",
    meaning: "Order, expression and discipline align, producing natural planning ability.",
    strengths: "Sequencing, budgeting, foresight, comfort with detail and documentation.",
    weaknesses: "Over planning can delay action until conditions look perfect.",
    career: "Project management, architecture, administration, law, finance and systems design.",
    relationships: "Brings security to family life through arrangements made in advance.",
    money: "Strong budgeting instinct. Long term goals are realistic and usually met.",
    health: "Mental tension from over scheduling. Unstructured time is genuinely restorative.",
    advice: "Set a decision deadline for every plan so preparation ends in execution.",
  },
  {
    key: "intellect",
    name: "Arrow of Intellect",
    line: [4, 9, 2],
    polarity: "strength",
    meaning: "The mental row is complete, so analysis, memory and intuition work together.",
    strengths: "Fast comprehension, retention, pattern recognition, sound judgement.",
    weaknesses: "Over thinking, and a tendency to argue from analysis rather than feeling.",
    career: "Research, medicine, technology, teaching, law and advisory work.",
    relationships: "Clear and articulate, though partners may want less analysis and more presence.",
    money: "Earnings follow expertise and reputation for accuracy.",
    health: "Mental fatigue and disturbed sleep when the mind stays active late.",
    advice: "Close the working day with a deliberate wind down so thinking has an off switch.",
  },
  {
    key: "emotional-balance",
    name: "Arrow of Emotional Balance",
    line: [3, 5, 7],
    polarity: "strength",
    meaning: "The emotional row is complete, giving steadiness through ups and downs.",
    strengths: "Composure, empathy, resilience after setbacks, calming influence on others.",
    weaknesses: "Emotions can be so well managed that others assume nothing affects you.",
    career: "Counselling, healthcare, leadership of people, negotiation, teaching and service roles.",
    relationships: "Safe and reassuring partner. Conflict rarely escalates in your presence.",
    money: "Financial choices stay calm during volatility, which protects capital.",
    health: "Generally balanced. Suppressed strain may surface as tension in the shoulders and sleep.",
    advice: "Share the difficult feeling too, not only the resolved conclusion.",
  },
  {
    key: "practicality",
    name: "Arrow of Practicality",
    line: [8, 1, 6],
    polarity: "strength",
    meaning: "The practical row is complete, so ideas are grounded in real material handling.",
    strengths: "Common sense, craftsmanship, reliability with resources and property.",
    weaknesses: "Imagination can be dismissed too quickly as impractical.",
    career: "Business, real estate, engineering, hospitality, manufacturing and trade.",
    relationships: "Shows love through provision and maintenance of daily life.",
    money: "Strong earning and asset instinct. Property and tangible assets perform well.",
    health: "Steady constitution. Sedentary routines are the main threat.",
    advice: "Keep one imaginative or artistic outlet alive alongside practical duties.",
  },
  {
    key: "activity",
    name: "Arrow of Activity",
    line: [2, 7, 6],
    polarity: "strength",
    meaning: "Sensitivity, insight and warmth combine into visible, sustained activity.",
    strengths: "High output, hands on involvement, ability to keep several tasks moving.",
    weaknesses: "Rest is resisted, and busyness can be mistaken for progress.",
    career: "Operations, hospitality, event work, healthcare delivery and field roles.",
    relationships: "Actively involved partner, present in the practical details of shared life.",
    money: "Income rises with activity levels, so pacing protects long term earning.",
    health: "Burnout risk. Recovery time must be scheduled, not improvised.",
    advice: "Measure results, not hours, and protect one full rest day each week.",
  },
  {
    key: "spirituality",
    name: "Arrow of Spirituality",
    line: [2, 5, 8],
    polarity: "strength",
    meaning: "The inner diagonal is complete, indicating natural faith and reflective depth.",
    strengths: "Inner steadiness, intuition, comfort with meaning and long horizons.",
    weaknesses: "Withdrawal from worldly demands when they feel shallow.",
    career: "Healing, counselling, research, teaching, philosophy and service organisations.",
    relationships: "Brings depth and acceptance. Partners feel understood rather than judged.",
    money: "Money is treated as a tool. Detachment helps decisions but can delay ambition.",
    health: "Benefits strongly from meditation, breath work and quiet routine.",
    advice: "Anchor inner practice in a daily schedule so it survives busy phases.",
  },
  {
    key: "compassion",
    name: "Arrow of Compassion",
    line: [2, 5, 8],
    polarity: "strength",
    meaning: "The same inner diagonal read outwardly: sensitivity is expressed as care for others.",
    strengths: "Empathy, patience with people, willingness to help without keeping score.",
    weaknesses: "Over giving, and difficulty refusing requests from those in need.",
    career: "Medical, social work, education, non profit and pastoral work.",
    relationships: "Forgiving and supportive. Boundaries need explicit definition.",
    money: "Generosity can outpace income unless a giving limit is set.",
    health: "Emotional fatigue from carrying other people's stress.",
    advice: "Decide in advance how much you can give, then give that fully.",
  },
  {
    key: "willpower",
    name: "Arrow of Willpower",
    line: [9, 5, 1],
    polarity: "strength",
    meaning: "Ambition, balance and self direction align, producing strong personal will.",
    strengths: "Focus, courage, ability to hold a decision against opposition.",
    weaknesses: "Domination in discussion and impatience with slower processes.",
    career: "Entrepreneurship, leadership, defence, surgery, sport and politics.",
    relationships: "Protective and decisive. Shared decision making needs conscious effort.",
    money: "Bold earning capacity. Risk limits should be written before acting.",
    health: "Pushes past warning signals. Blood pressure and inflammation deserve monitoring.",
    advice: "Invite one dissenting view before every major commitment.",
  },
  {
    key: "memory",
    name: "Arrow of Memory",
    line: [4, 9, 2],
    polarity: "caution",
    meaning: "The mental row is empty, so recall and mental filing need external support.",
    strengths: "Freedom from mental clutter, and openness to fresh approaches.",
    weaknesses: "Names, dates and details slip. Learning by memorisation is inefficient.",
    career: "Choose roles that reward judgement and relationship over recall, and use written systems.",
    relationships: "Forgotten commitments read as indifference, so record them.",
    money: "Payment dates and renewals need automation to avoid loss.",
    health: "Mental fatigue when too much is held in the head.",
    advice: "Externalise memory: one notebook, one calendar, one reminder system.",
  },
  {
    key: "isolation",
    name: "Arrow of Isolation",
    line: [3, 5, 7],
    polarity: "caution",
    meaning: "The emotional row is empty, indicating emotions handled privately and alone.",
    strengths: "Self reliance, calm exterior, ability to function while others react.",
    weaknesses: "Emotional distance, and delayed processing of hurt.",
    career: "Independent work suits, though team roles need deliberate communication.",
    relationships: "Partners may feel shut out during difficult phases.",
    money: "Financial stress is carried silently, which delays practical help.",
    health: "Internalised stress affects sleep and appetite.",
    advice: "Choose two people you update honestly, on a fixed rhythm.",
  },
  {
    key: "chaos",
    name: "Arrow of Chaos",
    line: [8, 1, 6],
    polarity: "caution",
    meaning: "The practical row is empty, so order in material life needs deliberate design.",
    strengths: "Comfortable with uncertainty, inventive when plans collapse.",
    weaknesses: "Disorganisation in documents, spaces and schedules.",
    career: "Pair with an organised partner or assistant and use checklists everywhere.",
    relationships: "Household disorder becomes a recurring friction point.",
    money: "Untracked spending is the largest financial leak.",
    health: "Irregular meals and sleep destabilise energy.",
    advice: "Build three simple systems: money, papers, and daily routine.",
  },
  {
    key: "frustration",
    name: "Arrow of Frustration",
    line: [9, 5, 1],
    polarity: "caution",
    meaning: "The will diagonal is empty, so effort and outcome often feel out of step.",
    strengths: "Humility, sensitivity to others, willingness to reconsider.",
    weaknesses: "Starting strongly and abandoning goals when resistance appears.",
    career: "Break work into short cycles with visible wins to sustain motivation.",
    relationships: "Unexpressed disappointment builds into sudden irritation.",
    money: "Income plateaus because ambitious asks are avoided.",
    health: "Suppressed frustration shows as tension headaches and restlessness.",
    advice: "Set small deadlines with accountability, and voice irritation early and calmly.",
  },
  {
    key: "skepticism",
    name: "Arrow of Skepticism",
    line: [2, 5, 8],
    polarity: "caution",
    meaning: "The inner diagonal is empty, so trust and faith are granted only after proof.",
    strengths: "Critical thinking, resistance to manipulation, strong evidence orientation.",
    weaknesses: "Cynicism, and difficulty accepting support that is genuinely offered.",
    career: "Excellent in audit, quality, research and risk. Rapport building needs attention.",
    relationships: "Reassurance is doubted, so partners feel tested.",
    money: "Missed opportunities from excessive caution.",
    health: "Chronic guardedness keeps the nervous system alert.",
    advice: "Run a small trust experiment monthly and observe the outcome honestly.",
  },
  {
    key: "procrastination",
    name: "Arrow of Procrastination",
    line: [4, 3, 8],
    polarity: "caution",
    meaning: "The planning column is empty, so beginnings are postponed and deadlines compress.",
    strengths: "Performs well under last minute pressure, decisive when time runs out.",
    weaknesses: "Avoidance of preparation, admin backlog, avoidable stress.",
    career: "Use fixed start times rather than fixed finish times for tasks.",
    relationships: "Delayed practical promises reduce trust over time.",
    money: "Late payments and unclaimed benefits cost money quietly.",
    health: "Stress spikes near deadlines, followed by exhaustion.",
    advice: "Start every task with a five minute first step booked in the calendar.",
  },
  {
    key: "passivity",
    name: "Arrow of Passivity",
    line: [2, 7, 6],
    polarity: "caution",
    meaning: "The activity column is empty, so initiative arrives only when clearly requested.",
    strengths: "Calm, unhurried, thoughtful before acting.",
    weaknesses: "Opportunities pass while waiting for the right moment.",
    career: "Set output targets rather than availability targets.",
    relationships: "Partner may carry most of the initiating and planning.",
    money: "Growth depends on being asked rather than on asking.",
    health: "Low activity affects circulation and mood.",
    advice: "Initiate one thing daily that nobody asked you to do.",
  },
  {
    key: "hesitation",
    name: "Arrow of Hesitation",
    line: [4, 5, 6],
    polarity: "caution",
    meaning: "The determination diagonal is empty, so follow through fluctuates with mood.",
    strengths: "Flexible, open to change of direction, not trapped by sunk cost.",
    weaknesses: "Half finished work, and decisions revisited too often.",
    career: "Choose milestone based roles with external review points.",
    relationships: "Indecision on shared plans creates uncertainty for the partner.",
    money: "Investments are entered and exited too early.",
    health: "Inconsistent routines dilute the benefit of good habits.",
    advice: "Commit to one decision for a fixed period before reviewing it.",
  },
];
