import type { Digit } from "./types";

/** Interpretation record for a digit that is present in the grid. */
export type NumberProfile = {
  digit: Digit;
  title: string;
  planet: string;
  element: string;
  positive: string[];
  negative: string[];
  career: string;
  leadership: string;
  relationships: string;
  marriage: string;
  communication: string;
  finance: string;
  health: string;
  spiritualLesson: string;
  tips: string[];
  careerFields: string[];
  luckyColours: string[];
  luckyDays: string[];
  luckyDirection: string;
};

export const NUMBER_PROFILES: Record<Digit, NumberProfile> = {
  1: {
    digit: 1,
    title: "The Initiator",
    planet: "Sun",
    element: "Fire",
    positive: ["Self starting", "Confident", "Decisive", "Ambitious", "Independent"],
    negative: ["Ego driven at times", "Impatient with slower people", "Resists being guided"],
    career: "Works best where the outcome carries a name and a signature. Founder roles, department heads and independent practice suit this energy.",
    leadership: "Leads from the front and sets the pace. Direction is clear, delegation needs conscious effort.",
    relationships: "Warm and protective, yet expects respect for personal space and personal decisions.",
    marriage: "Loyal partner who needs an equal, not an audience. Friction appears when authority is questioned publicly.",
    communication: "Direct, brief and result focused. Softening the opening line improves reception.",
    finance: "Earns through initiative and visibility. Income rises when personal branding is built deliberately.",
    health: "Vitality is generally strong. Watch heart rhythm habits, eye strain and long stretches without rest.",
    spiritualLesson: "Learn that leadership is service, not superiority.",
    tips: ["Ask for one opinion before every major decision", "Convert ambition into written milestones", "Give credit publicly, correct privately"],
    careerFields: ["Entrepreneurship", "Management", "Government", "Politics", "Consulting"],
    luckyColours: ["Gold", "Amber", "Deep orange"],
    luckyDays: ["Sunday", "Monday"],
    luckyDirection: "East",
  },
  2: {
    digit: 2,
    title: "The Harmoniser",
    planet: "Moon",
    element: "Water",
    positive: ["Sensitive", "Cooperative", "Intuitive", "Diplomatic", "Caring"],
    negative: ["Mood swings", "Over dependence on approval", "Avoids confrontation too long"],
    career: "Thrives in partnership work: counselling, care, hospitality, human resources and client relationships.",
    leadership: "Leads by consensus and emotional reading of the room rather than by command.",
    relationships: "Deeply attached and quick to sense unspoken tension. Needs reassurance in words, not only actions.",
    marriage: "Devoted and nurturing. Long silences after hurt are the main pattern to correct.",
    communication: "Gentle and indirect. Stating needs plainly prevents accumulated resentment.",
    finance: "Careful with money, prefers security over speculation. Joint ventures do well when terms are written.",
    health: "Digestion, sleep quality and fluid balance react quickly to emotional stress.",
    spiritualLesson: "Learn to give without losing the self.",
    tips: ["Name the feeling within a day of it appearing", "Keep one decision each week entirely your own", "Protect sleep as a health practice"],
    careerFields: ["Healing", "Teaching", "Medical", "Creative", "Sales"],
    luckyColours: ["Pearl white", "Silver", "Soft cream"],
    luckyDays: ["Monday", "Friday"],
    luckyDirection: "North west",
  },
  3: {
    digit: 3,
    title: "The Expander",
    planet: "Jupiter",
    element: "Ether",
    positive: ["Optimistic", "Expressive", "Knowledge seeking", "Generous", "Teacher by nature"],
    negative: ["Over commits", "Scatters focus", "Preaches instead of listening"],
    career: "Teaching, law, publishing, advisory and any field where explaining creates value.",
    leadership: "Leads by inspiring belief and raising standards. Follow through needs structure.",
    relationships: "Cheerful and encouraging, drawn to partners who value growth and learning.",
    marriage: "Steady and principled. Blunt honesty benefits from timing and tone.",
    communication: "Persuasive and expansive. Editing the message doubles its power.",
    finance: "Money arrives through knowledge, advice and reputation. Guard against over generosity.",
    health: "Weight, liver load and rich food are the recurring themes. Movement keeps this energy clear.",
    spiritualLesson: "Wisdom counts only when it is lived, not only spoken.",
    tips: ["Finish one project before starting the next", "Teach something monthly to sharpen clarity", "Keep a fixed giving budget"],
    careerFields: ["Teaching", "Writing", "Consulting", "Government", "Finance"],
    luckyColours: ["Saffron", "Mustard", "Warm yellow"],
    luckyDays: ["Thursday", "Sunday"],
    luckyDirection: "North east",
  },
  4: {
    digit: 4,
    title: "The Builder",
    planet: "Rahu",
    element: "Air",
    positive: ["Practical", "Systematic", "Unconventional problem solver", "Persistent", "Detail aware"],
    negative: ["Restlessness", "Sudden changes of plan", "Difficulty trusting slowly"],
    career: "Technology, logistics, research, analytics and any system that needs restructuring.",
    leadership: "Leads through process design. Excellent at fixing what others abandoned.",
    relationships: "Reliable in practice, guarded in words. Shows care through work done for the other person.",
    marriage: "Stable once trust is established. Needs a partner comfortable with a private nature.",
    communication: "Factual and precise. Adding warmth prevents an impression of coldness.",
    finance: "Income grows in steps, not leaps. Documentation and contracts protect this number.",
    health: "Nervous tension, irregular routine and screen fatigue are the main pressures.",
    spiritualLesson: "Stability is built by staying, not by starting again.",
    tips: ["Fix a daily anchor routine", "Review contracts before signing", "Give one honest compliment daily"],
    careerFields: ["Technology", "Management", "Business", "Finance", "Government"],
    luckyColours: ["Steel grey", "Slate blue", "Charcoal"],
    luckyDays: ["Saturday", "Wednesday"],
    luckyDirection: "South west",
  },
  5: {
    digit: 5,
    title: "The Balancer",
    planet: "Mercury",
    element: "Earth",
    positive: ["Adaptable", "Quick learner", "Commercially sharp", "Sociable", "Mediating"],
    negative: ["Restless with routine", "Over talks", "Spreads energy thin"],
    career: "Trade, marketing, negotiation, media and roles that reward fast thinking.",
    leadership: "Leads by connecting people and translating between groups.",
    relationships: "Playful and communicative, needs mental stimulation more than ceremony.",
    marriage: "Companionable and flexible. Boredom, not conflict, is the real risk.",
    communication: "Fluent and convincing. Listening in full is the growth area.",
    finance: "Multiple income streams suit this number. Impulse spending needs a rule.",
    health: "Skin, nerves and irregular meals respond first to overload.",
    spiritualLesson: "Freedom matures into responsibility.",
    tips: ["Keep one commitment for a full year", "Automate savings on income day", "Practise ten minutes of silence daily"],
    careerFields: ["Marketing", "Sales", "Business", "Creative", "Consulting"],
    luckyColours: ["Emerald green", "Turquoise", "Ivory"],
    luckyDays: ["Wednesday", "Friday"],
    luckyDirection: "North",
  },
  6: {
    digit: 6,
    title: "The Nurturer",
    planet: "Venus",
    element: "Water",
    positive: ["Aesthetic sense", "Responsible", "Warm", "Loyal", "Comfort creating"],
    negative: ["Indulgent", "Over involved in others' matters", "Avoids plain living"],
    career: "Design, hospitality, luxury goods, entertainment, wellness and family enterprise.",
    leadership: "Leads by caring for the team and by raising the quality of the environment.",
    relationships: "Romantic and attentive, values beauty, harmony and shared pleasures.",
    marriage: "Family centred and giving. Needs to state boundaries before exhaustion sets in.",
    communication: "Charming and diplomatic. Straight talk on money matters serves better.",
    finance: "Money flows steadily and leaves quickly through comfort spending. Budgets restore control.",
    health: "Throat, kidney load and sugar habits deserve attention.",
    spiritualLesson: "Love with clear boundaries is stronger than love without them.",
    tips: ["Set a monthly comfort budget", "Say no once a week without explaining", "Keep one creative practice alive"],
    careerFields: ["Creative", "Business", "Healing", "Marketing", "Teaching"],
    luckyColours: ["Rose", "Cream", "Soft pink"],
    luckyDays: ["Friday", "Wednesday"],
    luckyDirection: "South east",
  },
  7: {
    digit: 7,
    title: "The Seeker",
    planet: "Ketu",
    element: "Water",
    positive: ["Analytical", "Introspective", "Research minded", "Detached", "Perceptive"],
    negative: ["Withdraws under stress", "Doubts easily", "Delays emotional expression"],
    career: "Research, healing arts, spirituality, data work, investigation and specialised expertise.",
    leadership: "Leads quietly through depth of knowledge rather than visible authority.",
    relationships: "Selective and private. Trust grows slowly and then holds firmly.",
    marriage: "Loyal but needs solitude. Partners should read silence as recharge, not rejection.",
    communication: "Thoughtful and measured. Sharing conclusions earlier avoids misreadings.",
    finance: "Earns through specialised skill. Long term holdings suit better than active trading.",
    health: "Nervous system, sleep cycles and low grade anxiety are the recurring notes.",
    spiritualLesson: "Solitude is for clarity, not for hiding.",
    tips: ["Share one thought daily before it is fully formed", "Keep a fixed sleep window", "Turn research into a finished output"],
    careerFields: ["Healing", "Technology", "Writing", "Medical", "Consulting"],
    luckyColours: ["Indigo", "Smoke grey", "Deep violet"],
    luckyDays: ["Tuesday", "Saturday"],
    luckyDirection: "South",
  },
  8: {
    digit: 8,
    title: "The Organiser",
    planet: "Saturn",
    element: "Air",
    positive: ["Disciplined", "Enduring", "Fair", "Structure building", "Resilient"],
    negative: ["Rigid", "Slow to forgive", "Carries burden silently"],
    career: "Administration, law, real estate, mining, infrastructure and long horizon industries.",
    leadership: "Leads through accountability and long term planning.",
    relationships: "Dependable and steady, expresses affection through duty performed.",
    marriage: "Committed for the long run. Lightness and play need conscious scheduling.",
    communication: "Serious and economical. Adding appreciation improves closeness.",
    finance: "Wealth builds late and lasts. Debt discipline is the deciding factor.",
    health: "Joints, bones, teeth and chronic tension are the classic pressure points.",
    spiritualLesson: "Patience is a form of strength, not a punishment.",
    tips: ["Schedule rest as firmly as work", "Clear one old resentment each quarter", "Review debt every month"],
    careerFields: ["Government", "Finance", "Management", "Business", "Politics"],
    luckyColours: ["Deep blue", "Black", "Bronze"],
    luckyDays: ["Saturday", "Sunday"],
    luckyDirection: "West",
  },
  9: {
    digit: 9,
    title: "The Achiever",
    planet: "Mars",
    element: "Fire",
    positive: ["Courageous", "High energy", "Protective", "Goal driven", "Competitive"],
    negative: ["Quick anger", "Impulsive risk", "Impatience with delay"],
    career: "Defence, surgery, sport, engineering, real estate and any competitive field.",
    leadership: "Leads in crisis, decides fast and mobilises others quickly.",
    relationships: "Passionate and loyal, defends the partner strongly, needs to guard tone in conflict.",
    marriage: "Intense and committed. Cooling the first reaction protects the bond.",
    communication: "Forceful and clear. Lowering volume raises influence.",
    finance: "Earns aggressively and can spend the same way. Fixed investment habits balance this.",
    health: "Inflammation, blood pressure, accidents and overtraining need watching.",
    spiritualLesson: "Strength is proven by restraint.",
    tips: ["Insert a pause before every reply in conflict", "Train the body regularly to discharge energy", "Set risk limits before acting"],
    careerFields: ["Medical", "Technology", "Business", "Politics", "Sales"],
    luckyColours: ["Crimson", "Coral", "Copper"],
    luckyDays: ["Tuesday", "Sunday"],
    luckyDirection: "South",
  },
};

/** Interpretation record for a digit that is absent from the grid. */
export type MissingProfile = {
  digit: Digit;
  meaning: string;
  weakness: string;
  personality: string;
  careerImpact: string;
  relationshipImpact: string;
  financialImpact: string;
  health: string;
  lifeLesson: string;
  balancing: string;
  remedies: string[];
};

export const MISSING_PROFILES: Record<Digit, MissingProfile> = {
  1: {
    digit: 1,
    meaning: "Self assertion is a learned skill rather than a natural reflex here.",
    weakness: "Hesitation before claiming authorship of one's own work.",
    personality: "Capable yet waits for permission. Confidence rises sharply once a first independent success lands.",
    careerImpact: "Promotion arrives later than merit suggests because visibility is under managed.",
    relationshipImpact: "Preferences get postponed for the sake of peace, which builds quiet fatigue.",
    financialImpact: "Under charging and delayed price revisions reduce lifetime earnings.",
    health: "Low motivation phases and irregular energy when self worth dips.",
    lifeLesson: "Learn to stand in front of your own work.",
    balancing: "Take ownership of one visible responsibility every quarter.",
    remedies: ["Speak one clear preference daily", "Face morning light for ten minutes", "Keep a weekly record of personal wins"],
  },
  2: {
    digit: 2,
    meaning: "Emotional reading of situations needs deliberate attention.",
    weakness: "Sensitivity is either suppressed or arrives late, after the moment has passed.",
    personality: "Practical and composed, sometimes described as hard to read.",
    careerImpact: "Team dynamics can be misjudged, especially in client facing negotiation.",
    relationshipImpact: "Partners may feel unseen even when commitment is complete.",
    financialImpact: "Joint financial decisions get made without enough consultation.",
    health: "Sleep and digestion react when unspoken stress accumulates.",
    lifeLesson: "Learn that listening is an active contribution.",
    balancing: "Ask one feeling question in every important conversation.",
    remedies: ["Keep a short evening reflection note", "Practise slow breathing before difficult talks", "Spend time near water weekly"],
  },
  3: {
    digit: 3,
    meaning: "Structured learning and expression need building consciously.",
    weakness: "Ideas stay internal and lose their momentum.",
    personality: "Thoughtful yet reluctant to present. Depth exceeds visible confidence.",
    careerImpact: "Opportunities that reward articulation are missed by default.",
    relationshipImpact: "Explanations are short, which reads as disinterest.",
    financialImpact: "Advisory earnings and negotiation gains stay under used.",
    health: "Mental fog and low grade pessimism during heavy phases.",
    lifeLesson: "Learn that expressed knowledge multiplies.",
    balancing: "Write or speak one page on what you learned each week.",
    remedies: ["Read aloud for five minutes daily", "Study one subject to completion", "Mentor someone junior"],
  },
  4: {
    digit: 4,
    meaning: "Systems and follow through need external scaffolding.",
    weakness: "Plans start well and lose their order midway.",
    personality: "Creative and capable, resistant to procedure and record keeping.",
    careerImpact: "Execution gaps overshadow genuinely strong ideas.",
    relationshipImpact: "Practical promises slip, which erodes trust slowly.",
    financialImpact: "Untracked expenses and missed paperwork cost real money.",
    health: "Irregular routine affects sleep quality and stamina.",
    lifeLesson: "Learn that structure protects freedom.",
    balancing: "Keep one written system for money, time and tasks.",
    remedies: ["Plan the next day the night before", "Keep a single task list", "Declutter one area weekly"],
  },
  5: {
    digit: 5,
    meaning: "Balance between opposing demands has to be built rather than assumed.",
    weakness: "Swings between over involvement and withdrawal.",
    personality: "Sincere and committed, uncomfortable with rapid change.",
    careerImpact: "Adaptation to new tools and markets takes longer than peers.",
    relationshipImpact: "Middle ground in disagreement is hard to locate.",
    financialImpact: "Opportunities are judged late, after the window narrows.",
    health: "Stress settles in the stomach and the nervous system.",
    lifeLesson: "Learn flexibility without losing direction.",
    balancing: "Try one unfamiliar method every month on purpose.",
    remedies: ["Change one routine detail weekly", "Learn a new practical skill each quarter", "Walk daily to steady the nerves"],
  },
  6: {
    digit: 6,
    meaning: "Comfort, beauty and domestic harmony need conscious investment.",
    weakness: "Personal environment and personal appearance get deprioritised.",
    personality: "Duty first, pleasure later, sometimes never.",
    careerImpact: "Presentation and client experience receive less care than the work deserves.",
    relationshipImpact: "Romance becomes functional and loses its warmth.",
    financialImpact: "Either extreme thrift or sudden compensating splurges.",
    health: "Throat, kidneys and neglected rest become recurring complaints.",
    lifeLesson: "Learn that beauty and rest are practical needs.",
    balancing: "Reserve time and budget for home, art and appearance.",
    remedies: ["Keep fresh flowers or plants at home", "Plan one shared meal weekly", "Follow a simple grooming routine"],
  },
  7: {
    digit: 7,
    meaning: "Reflection and depth need protected time.",
    weakness: "Constant activity leaves little room for review.",
    personality: "Outwardly engaged, inwardly under examined.",
    careerImpact: "Specialisation is postponed in favour of general busyness.",
    relationshipImpact: "Deep conversation gets replaced by logistics.",
    financialImpact: "Decisions are taken quickly without research.",
    health: "Poor sleep quality and low tolerance for silence.",
    lifeLesson: "Learn that stillness produces clarity.",
    balancing: "Keep one silent hour weekly with no screen.",
    remedies: ["Sit quietly for ten minutes daily", "Keep a question journal", "Spend one evening monthly alone in nature"],
  },
  8: {
    digit: 8,
    meaning: "Discipline, order and long horizon patience are learned traits here.",
    weakness: "Boundaries and follow through waver under pressure.",
    personality: "Generous and warm, uncomfortable with rules and confrontation.",
    careerImpact: "Authority is under exercised, deadlines drift.",
    relationshipImpact: "Difficulty holding a stated limit leads to being over asked.",
    financialImpact: "Savings and long term assets build slowly.",
    health: "Joints, teeth and posture need preventive care.",
    lifeLesson: "Learn that limits are a form of respect.",
    balancing: "Set three non negotiable rules and hold them for a year.",
    remedies: ["Fix a daily start and end time for work", "Save a fixed amount on income day", "Practise strength or posture work"],
  },
  9: {
    digit: 9,
    meaning: "Drive and assertive energy need deliberate cultivation.",
    weakness: "Effort fades before the finish line.",
    personality: "Peaceful and cooperative, reluctant in competition.",
    careerImpact: "Ambitious targets are avoided, growth becomes gradual.",
    relationshipImpact: "Conflict is postponed until it grows larger than needed.",
    financialImpact: "Low risk appetite limits upside as much as it limits loss.",
    health: "Low stamina and sluggish circulation without regular movement.",
    lifeLesson: "Learn that healthy confrontation protects relationships.",
    balancing: "Complete one demanding goal with a public deadline.",
    remedies: ["Exercise vigorously three times a week", "Raise one difficult issue promptly", "Set a visible finish date for goals"],
  },
};

export const REPEAT_BANDS = {
  single: {
    label: "Balanced",
    reading: "The quality is available and workable. It supports you without dominating decisions.",
    intensity: 35,
  },
  double: {
    label: "Reinforced",
    reading: "The quality is strong and clearly visible to others. It becomes an identity marker and can crowd out softer traits.",
    intensity: 60,
  },
  triple: {
    label: "Dominant",
    reading: "The quality drives most reactions, including automatic ones. Its shadow side appears whenever pressure rises.",
    intensity: 82,
  },
  many: {
    label: "Overloaded",
    reading: "The quality is excessive and can override judgement. Conscious moderation matters more than further development.",
    intensity: 100,
  },
} as const;
