/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VarshphalRouteImport } from './routes/varshphal'
import { Route as TransitsRouteImport } from './routes/transits'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as SynastryRouteImport } from './routes/synastry'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RemediesRouteImport } from './routes/remedies'
import { Route as ProgressionsRouteImport } from './routes/progressions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PanchangRouteImport } from './routes/panchang'
import { Route as NumerologyRouteImport } from './routes/numerology'
import { Route as MuhuratRouteImport } from './routes/muhurat'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as KundliRouteImport } from './routes/kundli'
import { Route as HoroscopeRouteImport } from './routes/horoscope'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CompatibilityRouteImport } from './routes/compatibility'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AcceptTermsRouteImport } from './routes/accept-terms'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const VarshphalRoute = VarshphalRouteImport.update({
  id: '/varshphal',
  path: '/varshphal',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitsRoute = TransitsRouteImport.update({
  id: '/transits',
  path: '/transits',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const SynastryRoute = SynastryRouteImport.update({
  id: '/synastry',
  path: '/synastry',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RemediesRoute = RemediesRouteImport.update({
  id: '/remedies',
  path: '/remedies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionsRoute = ProgressionsRouteImport.update({
  id: '/progressions',
  path: '/progressions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchangRoute = PanchangRouteImport.update({
  id: '/panchang',
  path: '/panchang',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologyRoute = NumerologyRouteImport.update({
  id: '/numerology',
  path: '/numerology',
  getParentRoute: () => rootRouteImport,
} as any)
const MuhuratRoute = MuhuratRouteImport.update({
  id: '/muhurat',
  path: '/muhurat',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const KundliRoute = KundliRouteImport.update({
  id: '/kundli',
  path: '/kundli',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeRoute = HoroscopeRouteImport.update({
  id: '/horoscope',
  path: '/horoscope',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilityRoute = CompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptTermsRoute = AcceptTermsRouteImport.update({
  id: '/accept-terms',
  path: '/accept-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/ai': typeof AiRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/compatibility': typeof CompatibilityRoute
  '/history': typeof HistoryRoute
  '/horoscope': typeof HoroscopeRoute
  '/kundli': typeof KundliRoute
  '/learn': typeof LearnRoute
  '/muhurat': typeof MuhuratRoute
  '/numerology': typeof NumerologyRoute
  '/panchang': typeof PanchangRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progressions': typeof ProgressionsRoute
  '/remedies': typeof RemediesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synastry': typeof SynastryRoute
  '/tarot': typeof TarotRoute
  '/terms': typeof TermsRoute
  '/transits': typeof TransitsRoute
  '/varshphal': typeof VarshphalRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-terms': typeof AcceptTermsRoute
  '/ai': typeof AiRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/compatibility': typeof CompatibilityRoute
  '/history': typeof HistoryRoute
  '/horoscope': typeof HoroscopeRoute
  '/kundli': typeof KundliRoute
  '/learn': typeof LearnRoute
  '/muhurat': typeof MuhuratRoute
  '/numerology': typeof NumerologyRoute
  '/panchang': typeof PanchangRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progressions': typeof ProgressionsRoute
  '/remedies': typeof RemediesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synastry': typeof SynastryRoute
  '/tarot': typeof TarotRoute
  '/terms': typeof TermsRoute
  '/transits': typeof TransitsRoute
  '/varshphal': typeof VarshphalRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-terms': typeof AcceptTermsRoute
  '/ai': typeof AiRoute
  '/astrology': typeof AstrologyRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/compatibility': typeof CompatibilityRoute
  '/history': typeof HistoryRoute
  '/horoscope': typeof HoroscopeRoute
  '/kundli': typeof KundliRoute
  '/learn': typeof LearnRoute
  '/muhurat': typeof MuhuratRoute
  '/numerology': typeof NumerologyRoute
  '/panchang': typeof PanchangRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progressions': typeof ProgressionsRoute
  '/remedies': typeof RemediesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/synastry': typeof SynastryRoute
  '/tarot': typeof TarotRoute
  '/terms': typeof TermsRoute
  '/transits': typeof TransitsRoute
  '/varshphal': typeof VarshphalRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-terms'
    | '/ai'
    | '/astrology'
    | '/auth'
    | '/bookmarks'
    | '/compatibility'
    | '/history'
    | '/horoscope'
    | '/kundli'
    | '/learn'
    | '/muhurat'
    | '/numerology'
    | '/panchang'
    | '/pricing'
    | '/profile'
    | '/progressions'
    | '/remedies'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/synastry'
    | '/tarot'
    | '/terms'
    | '/transits'
    | '/varshphal'
    | '/admin'
    | '/saved'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-terms'
    | '/ai'
    | '/astrology'
    | '/auth'
    | '/bookmarks'
    | '/compatibility'
    | '/history'
    | '/horoscope'
    | '/kundli'
    | '/learn'
    | '/muhurat'
    | '/numerology'
    | '/panchang'
    | '/pricing'
    | '/profile'
    | '/progressions'
    | '/remedies'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/synastry'
    | '/tarot'
    | '/terms'
    | '/transits'
    | '/varshphal'
    | '/admin'
    | '/saved'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-terms'
    | '/ai'
    | '/astrology'
    | '/auth'
    | '/bookmarks'
    | '/compatibility'
    | '/history'
    | '/horoscope'
    | '/kundli'
    | '/learn'
    | '/muhurat'
    | '/numerology'
    | '/panchang'
    | '/pricing'
    | '/profile'
    | '/progressions'
    | '/remedies'
    | '/reports'
    | '/settings'
    | '/sitemap.xml'
    | '/synastry'
    | '/tarot'
    | '/terms'
    | '/transits'
    | '/varshphal'
    | '/_authenticated/admin'
    | '/_authenticated/saved'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptTermsRoute: typeof AcceptTermsRoute
  AiRoute: typeof AiRoute
  AstrologyRoute: typeof AstrologyRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  CompatibilityRoute: typeof CompatibilityRoute
  HistoryRoute: typeof HistoryRoute
  HoroscopeRoute: typeof HoroscopeRoute
  KundliRoute: typeof KundliRoute
  LearnRoute: typeof LearnRoute
  MuhuratRoute: typeof MuhuratRoute
  NumerologyRoute: typeof NumerologyRoute
  PanchangRoute: typeof PanchangRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressionsRoute: typeof ProgressionsRoute
  RemediesRoute: typeof RemediesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SynastryRoute: typeof SynastryRoute
  TarotRoute: typeof TarotRoute
  TermsRoute: typeof TermsRoute
  TransitsRoute: typeof TransitsRoute
  VarshphalRoute: typeof VarshphalRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/varshphal': {
      id: '/varshphal'
      path: '/varshphal'
      fullPath: '/varshphal'
      preLoaderRoute: typeof VarshphalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transits': {
      id: '/transits'
      path: '/transits'
      fullPath: '/transits'
      preLoaderRoute: typeof TransitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/synastry': {
      id: '/synastry'
      path: '/synastry'
      fullPath: '/synastry'
      preLoaderRoute: typeof SynastryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remedies': {
      id: '/remedies'
      path: '/remedies'
      fullPath: '/remedies'
      preLoaderRoute: typeof RemediesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressions': {
      id: '/progressions'
      path: '/progressions'
      fullPath: '/progressions'
      preLoaderRoute: typeof ProgressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchang': {
      id: '/panchang'
      path: '/panchang'
      fullPath: '/panchang'
      preLoaderRoute: typeof PanchangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerology': {
      id: '/numerology'
      path: '/numerology'
      fullPath: '/numerology'
      preLoaderRoute: typeof NumerologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muhurat': {
      id: '/muhurat'
      path: '/muhurat'
      fullPath: '/muhurat'
      preLoaderRoute: typeof MuhuratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundli': {
      id: '/kundli'
      path: '/kundli'
      fullPath: '/kundli'
      preLoaderRoute: typeof KundliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope': {
      id: '/horoscope'
      path: '/horoscope'
      fullPath: '/horoscope'
      preLoaderRoute: typeof HoroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibility': {
      id: '/compatibility'
      path: '/compatibility'
      fullPath: '/compatibility'
      preLoaderRoute: typeof CompatibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-terms': {
      id: '/accept-terms'
      path: '/accept-terms'
      fullPath: '/accept-terms'
      preLoaderRoute: typeof AcceptTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptTermsRoute: AcceptTermsRoute,
  AiRoute: AiRoute,
  AstrologyRoute: AstrologyRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  CompatibilityRoute: CompatibilityRoute,
  HistoryRoute: HistoryRoute,
  HoroscopeRoute: HoroscopeRoute,
  KundliRoute: KundliRoute,
  LearnRoute: LearnRoute,
  MuhuratRoute: MuhuratRoute,
  NumerologyRoute: NumerologyRoute,
  PanchangRoute: PanchangRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProgressionsRoute: ProgressionsRoute,
  RemediesRoute: RemediesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SynastryRoute: SynastryRoute,
  TarotRoute: TarotRoute,
  TermsRoute: TermsRoute,
  TransitsRoute: TransitsRoute,
  VarshphalRoute: VarshphalRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
