/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as PanchangRouteImport } from './routes/panchang'
import { Route as KundliRouteImport } from './routes/kundli'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as IndexRouteImport } from './routes/index'

const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const PanchangRoute = PanchangRouteImport.update({
  id: '/panchang',
  path: '/panchang',
  getParentRoute: () => rootRouteImport,
} as any)
const KundliRoute = KundliRouteImport.update({
  id: '/kundli',
  path: '/kundli',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRoute
  '/kundli': typeof KundliRoute
  '/panchang': typeof PanchangRoute
  '/tarot': typeof TarotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRoute
  '/kundli': typeof KundliRoute
  '/panchang': typeof PanchangRoute
  '/tarot': typeof TarotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRoute
  '/kundli': typeof KundliRoute
  '/panchang': typeof PanchangRoute
  '/tarot': typeof TarotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/astrology' | '/kundli' | '/panchang' | '/tarot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/astrology' | '/kundli' | '/panchang' | '/tarot'
  id: '__root__' | '/' | '/astrology' | '/kundli' | '/panchang' | '/tarot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstrologyRoute: typeof AstrologyRoute
  KundliRoute: typeof KundliRoute
  PanchangRoute: typeof PanchangRoute
  TarotRoute: typeof TarotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panchang': {
      id: '/panchang'
      path: '/panchang'
      fullPath: '/panchang'
      preLoaderRoute: typeof PanchangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kundli': {
      id: '/kundli'
      path: '/kundli'
      fullPath: '/kundli'
      preLoaderRoute: typeof KundliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstrologyRoute: AstrologyRoute,
  KundliRoute: KundliRoute,
  PanchangRoute: PanchangRoute,
  TarotRoute: TarotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
